{
	"fetchProtoError": "恢复X3原型时出错。表示法：{0}，Facet：{1}，外部设备：{2}，消息：{3}",
	"userRightsGenericError": "获取用户权限时出错"
}